image: node:latest

stages:
  - lint

eslint:
  stage: lint
  script:
    # Install ESLint in this docker container
    - npm install eslint
    # Configure ESLint (will read your .eslintrc file)
    - npx eslint --init
    # Run ESLint
    - npx eslint .